import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NextNProgressClient from "@/components/progress";
import ReactQueryConfig from "@/lib/react-query";
import NextAuthProvider from "@/lib/next-auth-provider";
import { RightDrawer } from "@/components/drawer";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/header";
import ReduxProvider from "@/hooks/redux-provider";
import ScrollToTop from "@/components/common/scroll-to-top";
import "react-lazy-load-image-component/src/effects/blur.css";
import 'react-lite-youtube-embed/dist/LiteYouTubeEmbed.css';
import Footer from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next Anime",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <NextAuthProvider>
              <ReactQueryConfig>
                <NextNProgressClient />
                <div className="min-h-screen flex-col flex">
                  <Header />
                  <div className="grow">
                    {children}
                  </div>
                  <Footer />
                </div>
                <ScrollToTop />
                <RightDrawer />
                <Toaster />
              </ReactQueryConfig>
            </NextAuthProvider>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
