import { z } from "zod";
import { SeasonConstant, StatusConstant, FormatConstant, SortConstant } from "@/utils/constant";
export const advancedSearchSchema = z.object({
  // query: z.string().optional(),
  season: z.enum(["WINTER", "SPRING", "SUMMER", "FALL", ""]).optional(),
  format: z.enum(["TV", "TV_SHORT", "MOVIE", "SPECIAL", "OVA", "ONA", "MUSIC", ""]).optional(),
  sort: z.enum([
    "POPULARITY_DESC",
    "POPULARITY",
    "TRENDING_DESC",
    "TRENDING",
    "UPDATED_AT_DESC",
    "UPDATED_AT",
    "START_DATE_DESC",
    "START_DATE",
    "END_DATE_DESC",
    "END_DATE",
    "FAVOURITES_DESC",
    "FAVOURITES",
    "SCORE_DESC",
    "SCORE",
    "TITLE_ROMAJI_DESC",
    "TITLE_ROMAJI",
    "TITLE_ENGLISH_DESC",
    "TITLE_ENGLISH",
    "TITLE_NATIVE_DESC",
    "TITLE_NATIVE",
    "EPISODES_DESC",
    "EPISODES",
    "ID",
    "ID_DESC",
    ""
  ]).optional(),
  status: z.enum(["RELEASING", "NOT_YET_RELEASED", "FINISHED", "CANCELLED", "HIATUS", ""]).optional(),
});